Calculator project (in MAUI)
TheCSharpAcademy/CodeReviews.Console.Calculator pull request #142
Opened 2024-03-01 16:43 UTC by wgrodzicki

This is my Calculator project. I did it using MAUI for the GUI layer, but overall it should satisfy all the requirements. I also added some extra features.

2024-03-07 20:45 UTC, Doc415 requested changes
Great work! Still I couldnt see the logging part of the calculator project. 
Did i missed it somewhere in the code ?

![image](https://github.com/TheCSharpAcademy/CodeReviews.Console.Calculator/assets/94632226/bcf6939f-6afe-4765-a3bd-8d68fe7b30ce)

2024-03-08 03:09 UTC, Doc415 approved these changes

2024-03-08 03:10 UTC, closed without merging

2024-03-08 14:20 UTC, wgrodzicki commented
Hi! Thanks! Regarding the lack of the logging part, I omitted it on purpose, since in the Microsoft tutorial it was eventually replaced by writing to JSON. So I decided to only include the features from the final version of the app.

2024-03-08 16:21 UTC, Doc415 commented
> Hi! Thanks! Regarding the lack of the logging part, I omitted it on purpose, since in the Microsoft tutorial it was eventually replaced by writing to JSON. So I decided to only include the features from the final version of the app.

We have approved your project. Looking forward for next one.