Project Submision
TheCSharpAcademy/CodeReviews.Console.Calculator pull request #23
Opened 2023-03-27 20:55 UTC by victoriensukarieh

2023-03-30 02:44 UTC, TheCSharpAcademy requested changes
@victoriensukarieh The project looks great and everything works fine. I like how you split the menu per number of operands. 😊

Since this is your second project, I'll be more strict in enforcing the removal of unnecessary comments and general code tidiness.

2023-03-30 02:44 UTC, TheCSharpAcademy commented on victoriensukarieh.Calculator/ConsoleCalculator/Models/Operation.cs
> +﻿namespace ConsoleCalculator.Models;
Please tidy up code formating: This button in the bottom of the code window is very useful for that: 😁
![image](https://user-images.githubusercontent.com/108711476/228714194-e1226102-3f3e-45a3-a05a-95f03f995313.png)

2023-03-30 02:44 UTC, TheCSharpAcademy commented on victoriensukarieh.Calculator/ConsoleCalculator/Program.cs
> +            // Declare variables and set to empty or zeros.
Please remove all comments that can be explained by the code itself.

2023-03-30 02:44 UTC, TheCSharpAcademy commented on victoriensukarieh.Calculator/ConsoleCalculator/Program.cs
> +using ConsoleCalculator.Models;
Please remove unecessary usings and add spacing between usings and namespace, and between namespace and class name, as per code conventions: 

![image](https://user-images.githubusercontent.com/108711476/228714775-f9c5f016-a425-4e8f-8cde-0a0d2a9c9f85.png)

2023-04-06 07:41 UTC, victoriensukarieh commented
@TheCSharpAcademy i am trying my best. i want to understand oop more and i wanna reach a point where starting an application and finishing it becomes automatic

2023-04-06 14:50 UTC, victoriensukarieh commented
i resolved the final issues and all is done @TheCSharpAcademy

2023-04-11 01:21 UTC, merged