Console Calculator, challenges done
TheCSharpAcademy/CodeReviews.Console.Calculator pull request #269
Opened 2024-10-02 17:45 UTC by PiotrrKubas

2024-10-03 10:10 UTC, chrisjamiecarter requested changes
Hey @PiotrrKubas 👋,

First of all, great job on your calculator application! 🎉 It’s clear you’ve put a lot of effort into this, and you’re making great progress.
I realize that much of your code likely follows the tutorial, but 
I have performed a peer review and have some praise, as well as a few suggestions:
- Great job on completing the challenges ⭐ 


**Solution Structure**
Re-read step 3 of the [Code Reviews](https://thecsharpacademy.com/article/52/code-reviews) academy page.
This will make it easier for code-reviewers to pull down and review your code in the future.
When submitting your code review pull request, all your solution files should be contained inside a new folder as per below:

✔️ 
```
.
└── [ProjectName].[GitHubUserName]/
    ├── [SolutionDirectory1]/
    ├── [SolutionDirectory2]/
    └── [ProjectName].sln
```

**Style Guide Compliance**
Remember that when you have finished a project, give it a polish pass. Pay attention to any code conventions in place, in this instance refer to the C# Academy's code-conventions page.
This is important as good code conventions/styling ensures consistency, makes your code easier for others to read and maintain, and improves your chances of getting a pull request reviewed and approved.

**Issues**
Unfortunately, I did spot an issue within your application.
Remember to test your application before submission. Attempt a Divide by Zero use case and see the results!

I suggest revisiting to understand and fix the issues, the commit and push your changes once resolved. This will notify me and I will (hopefully) approve this pull request.

Feel free to reach out if you have any questions or if you'd like to collaborate further on any of these points.

Thanks,
@chrisjamiecarter

2024-10-03 10:10 UTC, chrisjamiecarter commented on CalculatorLibrary/CalculatorLibrary.cs
> +                        writer.WriteValue("Divide");
As per the tutorial this is incorrect and will result in the wrong error 😄 .

Test and see for yourself 😱 !

After you have tested dividing by zero please update as per the microsoft documentation:
https://learn.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-console-part-2?view=vs-2022

2024-10-07 05:22 UTC, TheCSharpAcademy commented
@PiotrrKubas Let us know if you need help 👌🏻

2024-10-10 19:42 UTC, chrisjamiecarter requested changes
Hey @PiotrrKubas 👋 

Great job on the updates 🎉 .

So close to the final solution 🐎 !

However, unfortunately, there is still a slight issue ☹️ .

Again, I tried the test the divide by 0 use case ➗ .
The result will always be 8. Which I think is just how my terminal wants to display infinity ♾️ .

![image](https://github.com/user-attachments/assets/5cce40cb-7ecc-4b9d-b0e7-3a6adbc2c024)

The logic in your update isn't quite right 😵‍ .

```
case "/":
    bool isNum2Correct = double.IsInfinity(num1 / num2); // This should be: bool isNum2Correct = !double.IsInfinity(num1 / num2);
    while (isNum2Correct) // This should be: while (!isNum2Correct)
    {
        Console.Clear();
        Console.WriteLine("You cant divide by '0'");
        Console.WriteLine("Enter another divisor:");
        isNum2Correct = !double.TryParse(Console.ReadLine(), out num2);
    }
    result = num1 / num2;
    writer.WriteValue("Division");
    break;
```

**Or you could have done what I was expecting...** and move the line `writer.WriteValue("Division")` as per the tutorial 🤓 :

Your initial code:
![image](https://github.com/user-attachments/assets/33433d1e-8e6b-4d70-bac4-3f50b2c549da)

Expected:
![image](https://github.com/user-attachments/assets/6c212536-1b61-4a68-8bd9-907b25c8de02)

😄 
Hopefully this sheds some clearer light on the issue, and you can address and fix quickly!

Thanks,
@chrisjamiecarter

2024-10-13 16:28 UTC, chrisjamiecarter approved these changes
Perfect @PiotrrKubas 🎉 ,

I will go ahead and mark as approved, keep up the excellent work on the next projects! 😊

Best regards,
@chrisjamiecarter

2024-10-13 16:28 UTC, closed without merging