Initial Config
TheCSharpAcademy/CodeReviews.Console.Calculator pull request #46
Opened 2023-05-30 12:31 UTC by MR1R0B0T

Create Pull Request

2023-06-09 10:24 UTC, edvaudin requested changes
Congratulations on building a Calculator! The main theme of my comments will be focusing on validating user input. Currently, the user can crash the program in a few ways such as by entering non-numbers or by dividing by zero. The program should catch these and prompt the user to enter a valid input. 

Fixing the above will provide an opportunity to look at extracting some more methods. If you look closely at each of the operator methods, you will notice that they have several steps in common, such as prompting the user for input, collecting the user's input and then performing a calculation. These processes can be extracted into common methods. If you need any help with this, feel free to reach out to me (Xarvus on Discord).

There are some opportunities to reduce the number of Console.WriteLine() calls, however this is more minor.

I hope that all helps! Good luck!

2023-06-09 10:24 UTC, edvaudin commented on Calculator.MR1R0B0T/CalculatorApp/CalculatorApp/Program.cs
> +                    Environment.Exit(0);
Typing in a wrong input should not close the program, it should re-prompt the user for a valid input.

2023-06-09 10:24 UTC, edvaudin commented on Calculator.MR1R0B0T/CalculatorApp/CalculatorApp/Program.cs
> +            int num2 = Convert.ToInt32(Console.ReadLine());
This does not handle validating where the user has entered two numbers that can be parsed. Currently, there is an unhandled exception if the user types in an invalid input. You should consider creating a separate method that is responsible for validating that the user's input is indeed a number. If they do not enter a number, the program should re-prompt them for a valid input.

2023-06-09 10:24 UTC, edvaudin commented on Calculator.MR1R0B0T/CalculatorApp/CalculatorApp/Program.cs
> +            int quotient = num1 / num2;
This currently does not protect from the user entering 0 as the second number, which results in an unhandled exception. The program should ensure that either the user cannot enter 0 for the second number, or it should display NaN or something similar.

2023-07-19 05:10 UTC, TheCSharpAcademy commented
@MR1R0B0T I'm closing this for admin purposes, feel free to reopen if you want us to review.

2023-07-19 05:10 UTC, closed without merging