Add project file Calculator.yashsachdev
TheCSharpAcademy/CodeReviews.Console.Calculator pull request #6
Opened 2023-01-13 18:12 UTC by yashsachdev

2023-01-13 19:04 UTC, yashsachdev commented
Project Title
Calcualtor.yashsachdev

Challenges
 1.Create a functionality that will count the amount of times the calculator was used.
 2.Store a list with the latest calculations. And give the users the ability to delete that list.
 3.Allow the users to use the results in the list above to perform new calculations.
 4.Add extra calculations: Square Root, Taking the Power, 10x, Trigonometry functions.

Intuition:

challenge 1 : ---------- 
challenge 2: Create a function which stores the list using .add() function and use .clear() function to delete.
	     Used the switch statement to let user access the function.
challenge 3:----------------

challenge 4: extra extra operators to switch, used System.math.


Approach:

challenge 1 :Created a field called _count increament count each time the function runs.
challenge 2: Hindsight switch statement might have been a wrong approach should have called those functions in a different way.
		Validate the index of the list to prevent Indexout of bound exception.
challenge 3:	Display the list and index using DisplayResult() and ask the user to enter the index. 
		and used the list[index] as input .

challenge 4: -------------------------------


@TheCSharpAcademy Thank you for your time and effort in reviewing my code and helping me learn. Any Feedback would be appreciated.

2023-01-16 20:43 UTC, TheCSharpAcademy requested changes
It's looking great! I'm picking on the spacing issues because I like to cut these bad habits from the beginning. In terms of the code itself, the changes that are really important are the ones regarding refactoring your switch statements and commenting less.

2023-01-16 20:43 UTC, TheCSharpAcademy commented on Calculator.yashsachdev/Calculator.cs
> +﻿namespace Calculator.yashsachdev;
Please add one empty-line between a namespace declaration and a class.

2023-01-16 20:43 UTC, TheCSharpAcademy commented on Calculator.yashsachdev/Calculator.cs
> +
remove unnecessary empty line

2023-01-16 20:43 UTC, TheCSharpAcademy commented on Calculator.yashsachdev/Calculator.cs
> +
unnecessary empty line

2023-01-16 20:43 UTC, TheCSharpAcademy commented on Calculator.yashsachdev/Calculator.cs
> +            case "^":
This one is a bit personal but I like to keep my switch statements lean. You could refactor this way for example. You can quickly refactor it by selecting a block of code and using "ctrl + ." or right-clicking and choosing quick refactorings. 
![image](https://user-images.githubusercontent.com/108711476/212761924-c6de0af2-4ab7-43df-85fd-4ebe2a3c8be0.png)

![image](https://user-images.githubusercontent.com/108711476/212762063-ab277a5e-8500-495d-9eae-1be75ff748e4.png)

2023-01-16 20:43 UTC, TheCSharpAcademy commented on Calculator.yashsachdev/Calculator.cs
> +
unnecessary empty line

2023-01-16 20:43 UTC, TheCSharpAcademy commented on Calculator.yashsachdev/Calculator.cs
> +
remove unnecessary 89,90 empty lines

2023-01-16 20:43 UTC, TheCSharpAcademy commented on Calculator.yashsachdev/Calculator.cs
> +
remove unnecessary empty line

2023-01-16 20:43 UTC, TheCSharpAcademy commented on Calculator.yashsachdev/Program.cs
> +using Calculator;
Remove unused using.  
![image](https://user-images.githubusercontent.com/108711476/212762258-b28ae081-9ac0-4a3e-a9b1-91e1edf03ddd.png)

2023-01-16 20:43 UTC, TheCSharpAcademy commented on Calculator.yashsachdev/Program.cs
> +        calculator.DisplayResult(); //function to display list and its indexes.
It's ok to comment on code for learning, or when in development, but in general refrain from commenting, unless there's something here not explained by the code itself. If classes members (fields, methods, properties) are well-named, almost no comments are necessary.

2023-01-16 20:43 UTC, TheCSharpAcademy commented on Calculator.yashsachdev/Program.cs
> +
unnecessary empty line

2023-01-20 01:19 UTC, merged