Finished project
TheCSharpAcademy/CodeReviews.Console.Calculator pull request #69
Opened 2023-09-04 11:47 UTC by JamesLizamore

2023-09-05 01:10 UTC, TheCSharpAcademy requested changes
@JamesLizamore You'll need to remove your .git folder from inside your project and re-commit it. It was picked up as a submodule: 

![image](https://github.com/TheCSharpAcademy/CodeReviews.Console.Calculator/assets/108711476/5591e947-5f36-4a0b-b80d-cad0bc320620)

2023-09-05 05:22 UTC, JamesLizamore commented on Calculator.JamesLizamore/Calculator
I assume it wrong again as there is still a submodule?

2023-09-05 23:28 UTC, TheCSharpAcademy commented on Calculator.JamesLizamore/Calculator
Yes. Maybe just start again. 
1 - Delete the parent repository
2 - Clone it again
3 - Remove git folder from your project
4 - Copy your project into the cloned repo and create PR

2023-09-09 01:53 UTC, TheCSharpAcademy commented
@JamesLizamore Still hasn't worked. If you click on the "files changed" tab you can see what files you submitted for review, as per picture below. Could you please submit your own repository in your github so I can review it? I don't want to slow you down 😊

![image](https://github.com/TheCSharpAcademy/CodeReviews.Console.Calculator/assets/108711476/6f699d67-30ad-4a10-843f-c0b1375572c1)

2023-09-11 05:20 UTC, JamesLizamore commented
https://github.com/JamesLizamore/Calculator2

2023-09-12 05:25 UTC, TheCSharpAcademy commented
@JamesLizamore approved 😁

2023-09-12 05:25 UTC, closed without merging